Component not rendered
wooseok123/Front_End pull request #3
Opened 2022-04-24 05:39 UTC by wooseok123

리액트의 버전을 17로 다운그레이드하고
리액트 라우터 돔의 버전을 6으로 업그레이드 했습니다.

리액트 라우터 돔이 버전업되면서, Switch 대신에 Routes를 적용하였고,
리액트 버전이 다운그레이드 되면서 createRoot 대신 queryselector를 이용했습니다.

이에 url 주소에 따라 컴포넌트가 잘 렌더링 됨을 확인했습니다.

2022-04-24 09:09 UTC, 6lueparr0t commented
다운그레이드 보다는 업그레이드 해서 이슈를 해결해야되지 않을까요?

2022-04-28 14:38 UTC, OpusK requested changes

2022-04-28 14:38 UTC, OpusK commented on website/Build_Websites/react_firebase/firebasezoom/src/index.js
> +ReactDOM.render(<App />, document.getElementById("root"));
StrictMode 를 제거하셨는데, 이유가 있나요?

2022-04-28 14:38 UTC, OpusK commented on website/Build_Websites/react_firebase/firebasezoom/package.json
> +    "react": "^17.0.0",
react와 react-dom은 다운그레이드하고,
react-router-dom은 업그레이드한 이유가 무엇인가요?
향후 더 높은 버전의 react를 사용할 생각이라면, 이 부분은 다른 방식으로 해결하는 것이 좋아보입니다.

2022-04-29 04:12 UTC, wooseok123 commented
> 다운그레이드 보다는 업그레이드 해서 이슈를 해결해야되지 않을까요?

[레퍼런스](https://stackoverflow.com/questions/71832720/link-tag-inside-browserrouter-changes-only-the-url-but-doesnt-render-the-compo) 해당 레퍼런스를 참고해서 다운그레이드를 진행했었습니다!

근데 발가락님 말씀대로, 버전업을 해서 호환성 문제를 해결하는 것이 좋을 것 같습니다...
그렇다면 해당 PR은 close 해야 할까요??

2022-06-09 04:27 UTC, merged